spring:
    jpa:
        database: MYSQL

        hibernate:
            ddl-auto: update

    datasource:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        url: jdbc:mysql://mysql:3306/node
        username: admin
        password: admin
        driver-class-name: com.mysql.jdbc.Driver