spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost/test
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8300