spring:
  application:
    name: stock-db-serivce

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost/test
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8300

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost